### ISSUE TITLE
TROUBLESHOOTING

### ISSUE THREAD

**Issue by TrevDunn** [newyork-anthonyng/Cards_Against_Giphy#54]
[X] Login clicked while no text entered crashes server
    – Signing up with no text entered produces a 401 (Emulate this for login?)
[X] Failed login attempt returns error; locks up program
??""""
[X] Socket continuously emits 'show hand' continuously (even when in login screen)
    – script 288
[X] creating a new user does not generate a wins field in database

**Comment by sssyed** [comment]
You can also have over arching issues that have issues inside of them! https://guides.github.com/features/issues/#filtering
